### ISSUE TITLE
pico-hsm-tool urllib.error.HTTPError: HTTP Error 500: Internal Server Error

### ISSUE THREAD

**Issue by nimbius** [polhenarejos/pico-hsm#35]
looks like this error is back?

 ./pico-hsm-tool.py --pin 648219 initialize --so-pin 648219
********************************
*   PLEASE READ IT CAREFULLY   *
********************************

This tool will erase and reset your device. It will delete all private and secret keys.
Are you sure?
Pico HSM Tool v1.10
Author: Pol Henarejos
Report bugs to https://github.com/polhenarejos/pico-hsm/issues

[Press enter to confirm]
Public Point: 0486d34865bbf6b4aabf431dc94cbfdecf3901e4f2db315fe593cdd43080c258ddc6074f8ecfd11e7af3e535cc67da5c6b969025f928d2b96e895345582a0924e5
Traceback (most recent call last):
  File "/home/cicero/hsmtesting/pico-hsm/tools/./pico-hsm-tool.py", line 491, in <module>
    run()
  File "/home/cicero/hsmtesting/pico-hsm/tools/./pico-hsm-tool.py", line 488, in run
    main(args)
  File "/home/cicero/hsmtesting/pico-hsm/tools/./pico-hsm-tool.py", line 469, in main
    initialize(picohsm, args)
  File "/home/cicero/hsmtesting/pico-hsm/tools/./pico-hsm-tool.py", line 217, in initialize
    j = get_pki_data('cvc', data=data)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cicero/hsmtesting/pico-hsm/tools/./pico-hsm-tool.py", line 153, in get_pki_data
    response = urllib.request.urlopen(req)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

**Comment by dev-area** [comment]
same problem with debian 12 
it looks like a server problem
